#!/bin/bash

# IPv6 DNS Resolver Setup Script
# Configures DNS for IPv6-only servers
# Usage: bash setup-ipv6-dns.sh

echo "===================================="
echo "IPv6 DNS Resolver Setup"
echo "===================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "⚠️  This script needs root privileges."
    echo "Please run with: sudo bash $0"
    exit 1
fi

# Backup existing resolv.conf
echo "📦 Backing up current /etc/resolv.conf..."
if [ -f /etc/resolv.conf ]; then
    cp /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d_%H%M%S)
    echo "✅ Backup created"
else
    echo "ℹ️  No existing resolv.conf found"
fi

# Configure DNS servers with NAT64/DNS64 for IPv4 connectivity
echo ""
echo "🔧 Configuring DNS64 servers (enables IPv4 site access via IPv6)..."
cat > /etc/resolv.conf <<EOF
# IPv6 DNS64 Configuration (NAT64 enabled)
# Generated by setup-ipv6-dns.sh on $(date)
# DNS64 allows IPv6-only servers to reach IPv4-only sites like GitHub

# DNS64 servers with NAT64 support
nameserver 2a01:4f8:c2c:123f::1
nameserver 2a00:1098:2b::1
nameserver 2a01:4f9:c010:3f02::1

# Fallback: Google Public DNS (IPv6)
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844

# Fallback: Google Public DNS (IPv4)
nameserver 8.8.8.8
nameserver 8.8.4.4
EOF

echo "✅ DNS64 servers configured"

# Test DNS resolution
echo ""
echo "🧪 Testing DNS resolution..."
if ping -c 2 -W 3 google.com > /dev/null 2>&1; then
    echo "✅ DNS resolution working!"
else
    echo "⚠️  DNS test failed. Trying alternative configuration..."
    
    # Try with Cloudflare DNS
    cat > /etc/resolv.conf <<EOF
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
nameserver 1.1.1.1
nameserver 1.0.0.1
EOF
    
    if ping -c 2 -W 3 google.com > /dev/null 2>&1; then
        echo "✅ DNS working with Cloudflare DNS"
    else
        echo "❌ DNS still not working. Check your network connectivity."
    fi
fi

# Make persistent (systemd-resolved)
echo ""
echo "🔒 Making DNS configuration persistent..."
if [ -f /etc/systemd/resolved.conf ]; then
    cp /etc/systemd/resolved.conf /etc/systemd/resolved.conf.backup.$(date +%Y%m%d_%H%M%S)
    
    cat > /etc/systemd/resolved.conf <<EOF
[Resolve]
DNS=2001:4860:4860::8888 2001:4860:4860::8844 8.8.8.8
FallbackDNS=8.8.4.4 2606:4700:4700::1111
#DNSSEC=allow-downgrade
DNSOverTLS=no
EOF
    
    systemctl restart systemd-resolved 2>/dev/null
    echo "✅ systemd-resolved configured"
else
    echo "ℹ️  systemd-resolved not found, using /etc/resolv.conf only"
fi

# Prevent resolv.conf from being overwritten
if [ -L /etc/resolv.conf ]; then
    echo ""
    echo "🔗 /etc/resolv.conf is a symlink"
    echo "   Your system may overwrite DNS settings on reboot"
    echo "   To make permanent, consider unlinking:"
    echo "   sudo unlink /etc/resolv.conf"
    echo "   sudo systemctl restart systemd-resolved"
fi

echo ""
echo "===================================="
echo "✅ Setup Complete!"
echo "===================================="
echo ""
echo "Current DNS servers:"
cat /etc/resolv.conf | grep nameserver
echo ""
echo "Test your connection:"
echo "  apt-get update"
echo "  ping google.com"
echo ""
