#!/usr/bin/env bash
#
# setup-ipv6-dns.sh
#
# Configures DNS64/NAT64 resolution on IPv6-only hosts so they can reach
# IPv4-only destinations (e.g. github.com) by synthesizing AAAA records.
#
# Usage:
#   sudo bash setup-ipv6-dns.sh [--fallback-only] [--unlock] [--help]
#
# Options:
#   --fallback-only   Skip primary DNS64 servers, use go6lab public NAT64 directly
#   --unlock          Just remove the immutable flag from /etc/resolv.conf and exit
#   --help            Show this help text
#
# Repository: pgwiz/ipv6-vps-dns-resolver
#
set -euo pipefail
trap 'echo "❌ Error on line $LINENO. Aborting." >&2' ERR

# ----------------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------------
readonly RESOLV_CONF="/etc/resolv.conf"
readonly RESOLVED_DROPIN_DIR="/etc/systemd/resolved.conf.d"
readonly RESOLVED_DROPIN="${RESOLVED_DROPIN_DIR}/disable-stub.conf"
readonly BACKUP_DIR="/var/backups/ipv6-dns-resolver"
readonly LOG_FILE="/var/log/ipv6-dns-resolver.log"
readonly TEST_HOST="https://github.com"
readonly CURL_TIMEOUT=8

readonly PRIMARY_DNS64=(
    "2a01:4f8:c2c:123f::1"
    "2a00:1098:2b::1"
    "2a01:4f9:c010:3f02::1"
)
readonly FALLBACK_DNS64=(
    "2001:67c:2b0::4"
    "2001:67c:2b0::6"
)

USE_FALLBACK_ONLY=false

# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------
log() {
    local level="$1"; shift
    local msg="$*"
    local ts
    ts="$(date '+%Y-%m-%d %H:%M:%S')"
    printf '[%s] [%s] %s\n' "$ts" "$level" "$msg" | tee -a "$LOG_FILE"
}

info()  { log "INFO"  "ℹ️  $*"; }
ok()    { log "OK"    "✅ $*"; }
warn()  { log "WARN"  "⚠️  $*"; }
error() { log "ERROR" "❌ $*"; }

usage() {
    grep '^#' "$0" | sed -n '2,13p' | sed 's/^# \{0,1\}//'
    exit 0
}

require_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        error "This script must be run as root."
        echo "Please run with: sudo bash $0" >&2
        exit 1
    fi
}

write_resolv_conf() {
    local -n servers_ref=$1
    local header="$2"

    rm -f "$RESOLV_CONF"
    {
        echo "# IPv6 DNS64 configuration (NAT64 enabled)"
        echo "# Generated by setup-ipv6-dns.sh on $(date '+%Y-%m-%d %H:%M:%S')"
        echo "# $header"
        echo ""
        for ns in "${servers_ref[@]}"; do
            echo "nameserver ${ns}"
        done
    } > "$RESOLV_CONF"
}

test_nat64() {
    local http_code
    http_code=$(curl -6 -s -o /dev/null -w '%{http_code}' --max-time "$CURL_TIMEOUT" "$TEST_HOST" || true)
    [[ "$http_code" == "200" ]]
}

# ----------------------------------------------------------------------------
# Steps
# ----------------------------------------------------------------------------
unlock_resolv_conf() {
    if chattr -i "$RESOLV_CONF" 2>/dev/null; then
        ok "Removed immutable flag from ${RESOLV_CONF}."
    else
        info "No immutable flag was set on ${RESOLV_CONF} (or filesystem doesn't support chattr)."
    fi
}

backup_resolv_conf() {
    info "Backing up current ${RESOLV_CONF}..."
    mkdir -p "$BACKUP_DIR"

    if [[ -f "$RESOLV_CONF" || -L "$RESOLV_CONF" ]]; then
        local backup_path="${BACKUP_DIR}/resolv.conf.$(date '+%Y%m%d_%H%M%S')"
        cp -L "$RESOLV_CONF" "$backup_path" 2>/dev/null \
            && ok "Backup saved to ${backup_path}" \
            || warn "Could not create backup (continuing anyway)."
    else
        info "No existing ${RESOLV_CONF} found; nothing to back up."
    fi
}

disable_resolved_stub() {
    info "Checking systemd-resolved stub listener..."

    if ! systemctl is-active --quiet systemd-resolved 2>/dev/null; then
        info "systemd-resolved is not active; skipping stub-disable step."
        return
    fi

    mkdir -p "$RESOLVED_DROPIN_DIR"
    cat > "$RESOLVED_DROPIN" <<-'EOF'
	[Resolve]
	DNSStubListener=no
	EOF

    systemctl restart systemd-resolved 2>/dev/null || true
    ok "systemd-resolved stub listener disabled."
}

configure_dns64() {
    info "Writing static DNS64 resolv.conf (primary servers)..."
    write_resolv_conf PRIMARY_DNS64 "DNS64 allows IPv6-only servers to reach IPv4-only sites like GitHub"
    ok "Primary DNS64 servers configured."
}

verify_connectivity() {
    info "Testing DNS64/NAT64 by fetching ${TEST_HOST} (IPv4-only host)..."

    if test_nat64; then
        ok "DNS64/NAT64 working — ${TEST_HOST} reachable via synthesized IPv6."
        return 0
    fi

    warn "Primary DNS64 servers failed. Trying fallback (go6lab public NAT64)..."
    write_resolv_conf FALLBACK_DNS64 "Fallback: go6lab public NAT64"

    if test_nat64; then
        ok "DNS64/NAT64 working with go6lab fallback."
        return 0
    fi

    error "DNS64/NAT64 still not working. Check upstream routing/firewall rules."
    return 1
}

lock_resolv_conf() {
    info "Locking ${RESOLV_CONF} against overwrites (netplan, cloud-init, resolved)..."
    if chattr +i "$RESOLV_CONF" 2>/dev/null; then
        ok "Locked with chattr +i. To unlock: sudo bash $0 --unlock"
    else
        warn "Could not set immutable flag (filesystem may not support it)."
    fi
}

print_summary() {
    echo ""
    echo "===================================="
    echo "✅ Setup Complete"
    echo "===================================="
    echo ""
    echo "Current DNS servers:"
    grep '^nameserver' "$RESOLV_CONF" || true
    echo ""
    echo "Test your connection manually with:"
    echo "  curl -6 -v ${TEST_HOST}"
    echo ""
    echo "Log file: ${LOG_FILE}"
    echo ""
}

# ----------------------------------------------------------------------------
# Argument parsing
# ----------------------------------------------------------------------------
for arg in "$@"; do
    case "$arg" in
        --help) usage ;;
        --fallback-only) USE_FALLBACK_ONLY=true ;;
        --unlock)
            require_root
            unlock_resolv_conf
            exit 0
            ;;
        *)
            error "Unknown option: $arg"
            usage
            ;;
    esac
done

# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------
main() {
    require_root
    mkdir -p "$(dirname "$LOG_FILE")"
    touch "$LOG_FILE"

    echo "===================================="
    echo "IPv6 DNS64/NAT64 Resolver Setup"
    echo "===================================="
    echo ""

    unlock_resolv_conf
    backup_resolv_conf
    disable_resolved_stub

    if [[ "$USE_FALLBACK_ONLY" == true ]]; then
        info "Skipping primary DNS64 servers (--fallback-only set)."
        write_resolv_conf FALLBACK_DNS64 "Fallback: go6lab public NAT64 (forced)"
        test_nat64 && ok "DNS64/NAT64 working with go6lab fallback." \
            || error "DNS64/NAT64 still not working. Check upstream routing/firewall rules."
    else
        configure_dns64
        verify_connectivity || true
    fi

    lock_resolv_conf
    print_summary
}

main "$@"
[Resolve]
DNSStubListener=no
EOF
    systemctl restart systemd-resolved 2>/dev/null
    echo "✅ systemd-resolved stub disabled"
fi

# Remove symlink/file and write a static resolv.conf directly
echo ""
echo "🔧 Writing static DNS64 resolv.conf..."
rm -f /etc/resolv.conf
cat > /etc/resolv.conf <<EOF
# IPv6 DNS64 Configuration (NAT64 enabled)
# Generated by setup-ipv6-dns.sh on $(date)
# DNS64 allows IPv6-only servers to reach IPv4-only sites like GitHub

nameserver 2a01:4f8:c2c:123f::1
nameserver 2a00:1098:2b::1
nameserver 2a01:4f9:c010:3f02::1
EOF
echo "✅ DNS64 servers configured"

# Real test: resolve and reach an IPv4-only site via NAT64
echo ""
echo "🧪 Testing DNS64/NAT64 (fetching github.com, an IPv4-only host)..."
if curl -6 -s -o /dev/null -w "%{http_code}" --max-time 8 https://github.com | grep -q "200"; then
    echo "✅ DNS64/NAT64 working! github.com reachable via synthesized IPv6."
else
    echo "⚠️  Primary DNS64 servers failed. Trying fallback (go6lab public NAT64)..."
    cat > /etc/resolv.conf <<EOF
nameserver 2001:67c:2b0::4
nameserver 2001:67c:2b0::6
EOF
    if curl -6 -s -o /dev/null -w "%{http_code}" --max-time 8 https://github.com | grep -q "200"; then
        echo "✅ DNS64/NAT64 working with go6lab fallback."
    else
        echo "❌ DNS64/NAT64 still not working. Check upstream routing/firewall."
    fi
fi

# Lock resolv.conf so nothing overwrites it (netplan, cloud-init, resolved)
echo ""
echo "🔒 Locking /etc/resolv.conf against overwrites..."
if chattr +i /etc/resolv.conf 2>/dev/null; then
    echo "✅ Locked (chattr +i). To unlock later: sudo chattr -i /etc/resolv.conf"
else
    echo "⚠️  Could not set immutable flag (filesystem may not support it)"
fi

echo ""
echo "===================================="
echo "✅ Setup Complete!"
echo "===================================="
echo ""
echo "Current DNS servers:"
grep nameserver /etc/resolv.conf
echo ""
echo "Test your connection:"
echo "  curl -6 -v https://github.com"
echo ""
