#!/bin/bash

# IPv6 DNS64/NAT64 Resolver Setup Script
# Configures DNS64 for IPv6-only servers to reach IPv4-only sites (e.g. GitHub)
# Usage: sudo bash setup-ipv6-dns.sh

echo "===================================="
echo "IPv6 DNS64/NAT64 Resolver Setup"
echo "===================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "⚠️  This script needs root privileges."
    echo "Please run with: sudo bash $0"
    exit 1
fi

# Unlock resolv.conf if previously locked by this script
chattr -i /etc/resolv.conf 2>/dev/null

# Backup existing resolv.conf
echo "📦 Backing up current /etc/resolv.conf..."
if [ -f /etc/resolv.conf ] || [ -L /etc/resolv.conf ]; then
    cp -L /etc/resolv.conf /etc/resolv.conf.backup.$(date +%Y%m%d_%H%M%S) 2>/dev/null
    echo "✅ Backup created"
else
    echo "ℹ️  No existing resolv.conf found"
fi

# Stop systemd-resolved from intercepting/rewriting resolv.conf
echo ""
echo "🔧 Disabling systemd-resolved stub interference..."
if systemctl is-active --quiet systemd-resolved; then
    mkdir -p /etc/systemd/resolved.conf.d
    cat > /etc/systemd/resolved.conf.d/disable-stub.conf <<EOF
[Resolve]
DNSStubListener=no
EOF
    systemctl restart systemd-resolved 2>/dev/null
    echo "✅ systemd-resolved stub disabled"
fi

# Remove symlink/file and write a static resolv.conf directly
echo ""
echo "🔧 Writing static DNS64 resolv.conf..."
rm -f /etc/resolv.conf
cat > /etc/resolv.conf <<EOF
# IPv6 DNS64 Configuration (NAT64 enabled)
# Generated by setup-ipv6-dns.sh on $(date)
# DNS64 allows IPv6-only servers to reach IPv4-only sites like GitHub

nameserver 2a01:4f8:c2c:123f::1
nameserver 2a00:1098:2b::1
nameserver 2a01:4f9:c010:3f02::1
EOF
echo "✅ DNS64 servers configured"

# Real test: resolve and reach an IPv4-only site via NAT64
echo ""
echo "🧪 Testing DNS64/NAT64 (fetching github.com, an IPv4-only host)..."
if curl -6 -s -o /dev/null -w "%{http_code}" --max-time 8 https://github.com | grep -q "200"; then
    echo "✅ DNS64/NAT64 working! github.com reachable via synthesized IPv6."
else
    echo "⚠️  Primary DNS64 servers failed. Trying fallback (go6lab public NAT64)..."
    cat > /etc/resolv.conf <<EOF
nameserver 2001:67c:2b0::4
nameserver 2001:67c:2b0::6
EOF
    if curl -6 -s -o /dev/null -w "%{http_code}" --max-time 8 https://github.com | grep -q "200"; then
        echo "✅ DNS64/NAT64 working with go6lab fallback."
    else
        echo "❌ DNS64/NAT64 still not working. Check upstream routing/firewall."
    fi
fi

# Lock resolv.conf so nothing overwrites it (netplan, cloud-init, resolved)
echo ""
echo "🔒 Locking /etc/resolv.conf against overwrites..."
if chattr +i /etc/resolv.conf 2>/dev/null; then
    echo "✅ Locked (chattr +i). To unlock later: sudo chattr -i /etc/resolv.conf"
else
    echo "⚠️  Could not set immutable flag (filesystem may not support it)"
fi

echo ""
echo "===================================="
echo "✅ Setup Complete!"
echo "===================================="
echo ""
echo "Current DNS servers:"
grep nameserver /etc/resolv.conf
echo ""
echo "Test your connection:"
echo "  curl -6 -v https://github.com"
echo ""
